### ISSUE TITLE
Provide way to enter TODO information into Dockerfile

### ISSUE THREAD

**Issue by chrisnegus** [ashcrow/image-helpgen#3]
When running "image-helpgen dockerfile", the resulting help.md file shows TODO in places where descriptions of environment variables, ports, and volumes are needed. I'd like to suggest there be a way to add that information to the Dockerfile (associated with each of those items), so no manual editing of the resulting help.md file is needed after the tool is run.

**Comment by ashcrow** [comment]
Agreed. First steps here is to find out how someone should be adding in the comments to the `Dockerfile`. Once we figure that out we can implement the parsing of said comments to replace TODO's.

**Comment by ashcrow** [comment]
@chrisnegus do you have any ideas as to how to annotate the Dockerfile to include this extra information?

**Comment by ashcrow** [comment]
I've been thinking a little bit more about this and this was what came to mind:

## Comments above items following a specific format
### Example: ENV
```
# A would put a description here
ENV A=B
# Documentation for F
ENV F="asd"
```
### Example: VOLUME/PORT
For items with expected-but-configurable items we follow this format
`# $THING->$RECOMMENDED $DESCRIPTION`
```
# /rootfs->/ Description would go here
VOLUME /rootfs
# 8080->80 Web server listening port
EXPOSE 8080
```

## Downside
The downside here is that people would be discouraged from forcing things into a single line. For example, the format wouldn't work for:
```
VOLUME /rootfs /etc /var/run/
```
since documenting all three in one line would be hard to read and rough to parse properly. I guess we *could* allow multiple items on a single line and still have multiple comments like so:
```
# /rootfs->/ Mount of rootfs
# /etc->/etc Mount in of the config directory
# /var/run->/var/run Mount in of the run directory
VOLUME /rootfs /etc /var/run/
```

@chrisnegus thoughts?

**Comment by chrisnegus** [comment]
I would be fine with either of those two ways. If it's easier to parse with each VOLUME on a separate line, then I don't see a problem with recommending that. I guess the goal is to do whatever makes it most likely that the help page could be fully generated automatically.

**Comment by ashcrow** [comment]
I'm trying these out today
